# Generated by Django 5.1 on 2024-11-01 15:49

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('short_intro', models.CharField(blank=True, max_length=200, null=True, verbose_name='Short Intro')),
                ('bio', models.TextField(blank=True, verbose_name='Bio')),
                ('location', models.CharField(blank=True, max_length=100, verbose_name='Location')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='photos/%Y/%m/%d/', verbose_name='Photo')),
                ('updated', models.DateTimeField(auto_now=True)),
                ('social_github', models.URLField(blank=True, verbose_name='Social Github')),
                ('social_stackoverflow', models.URLField(blank=True, verbose_name='Social Stackoverflow')),
                ('social_twitter', models.URLField(blank=True, verbose_name='Social Twitter')),
                ('social_linkedin', models.URLField(blank=True, verbose_name='Social LinkedIn')),
                ('social_website', models.URLField(blank=True, verbose_name='Social Website')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skills', to='profiles.profile')),
            ],
            options={
                'ordering': ['-created'],
            },
        ),
        migrations.AddIndex(
            model_name='profile',
            index=models.Index(fields=['-created'], name='profiles_pr_created_a1bd98_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='skill',
            unique_together={('user', 'name')},
        ),
    ]
