# Generated by Django 5.1 on 2025-07-10 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_alter_tag_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='featured_image',
            field=models.ImageField(null=True, upload_to='featured_image/'),
        ),
    ]
