# Generated by Django 5.1 on 2024-11-01 15:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_otp_expiry'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='otp',
            name='expiry',
        ),
    ]
