# Generated by Django 5.1 on 2025-07-10 07:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_user_created_user_deleted_at_user_is_deleted'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ['-created_at'], 'permissions': [('can_toggle_user_status', 'Can toggle user active status')]},
        ),
    ]
