#!/bin/bash

# Stop the script immediately if any command fails
set -e

echo "Running migrations..."
python manage.py migrate --noinput

echo "Creating sample data..."
python manage.py initd

# Collect static files
echo "Collecting static files..."
python manage.py collectstatic --noinput

RUNTIME_PORT=${PORT:-8080}
RUNTIME_HOST=${HOST:-0.0.0.0}

gunicorn devsearch.wsgi:application --bind $RUNTIME_HOST:$RUNTIME_PORT