# Generated by Django 5.1 on 2024-11-01 15:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0004_alter_book_publisher'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Book',
        ),
        migrations.DeleteModel(
            name='Publisher',
        ),
    ]
